ALTER TABLE "Trade"
ADD COLUMN IF NOT EXISTS "claimedAt" TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS "claimedBy" TEXT,
ADD COLUMN IF NOT EXISTS "claimId" TEXT;

CREATE INDEX IF NOT EXISTS "Trade_claimId_idx" ON "Trade"("claimId");
